version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/wa-translator/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/wa-translator/cloudflare"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5

  - package-ecosystem: "bundler"
    directory: "/wa-translator/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:45"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/wa-translator/mobile/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Phnom_Penh"
    open-pull-requests-limit: 5
